---
- name: Install Prometheus
  hosts: grafana_prometheous
  become: true
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name: wget
        state: present

    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /bin/false

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Download Prometheus tarball
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus tarball
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus binary to /usr/local/bin
      command:
        cmd: mv /tmp/prometheus-2.41.0.linux-amd64/prometheus /usr/local/bin/
      become: yes

    - name: Move Promtool binary to /usr/local/bin
      command:
        cmd: mv /tmp/prometheus-2.41.0.linux-amd64/promtool /usr/local/bin/
      become: yes

    - name: Move Prometheus configuration file to /etc/prometheus
      command:
        cmd: mv /tmp/prometheus-2.41.0.linux-amd64/prometheus.yml /etc/prometheus/
      become: yes

    - name: Move Prometheus consoles directory to /etc/prometheus
      command:
        cmd: rsync -a /tmp/prometheus-2.41.0.linux-amd64/consoles/ /etc/prometheus/consoles/
      become: yes

    - name: Move Prometheus console_libraries directory to /etc/prometheus
      command:
        cmd: rsync -a /tmp/prometheus-2.41.0.linux-amd64/console_libraries/ /etc/prometheus/console_libraries/
      become: yes

    - name: Create Prometheus systemd service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file /etc/prometheus/prometheus.yml \
            --storage.tsdb.path /var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply Prometheus service
      systemd:
        daemon_reload: yes

    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

